config/routes.rb
Rails.application.routes.draw do
  root 'listings#index'
  resources :listings
 get 'signup', to:'users#new'
  resources :users, except: [:new]




end

app/models/listing.rb
class Listing < ActiveRecord::Base
validates_presence_of :title,length:{maximum:50,minimum:5}
validates_presence_of :description,length:{maximum:200,minimum:10}
validates_presence_of :city
validates_presence_of :contact
validates_presence_of :address
validates_presence_of :price

end

app/models/user.rb
class User< ActiveRecord::Base
    validates_presence_of :username,length:{maximum:15,minimum:5}
    validates_presence_of :password,length:{maximum:25,minimum:8}
    validates_presence_of :email
    validates_presence_of :city
    validates_presence_of :contact
    validates_presence_of :address
    has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
    do_not_validate_attachment_file_type :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def index
    @listings=Listing.all

  end
  def new
  @listing= Listing.new
  end
  def create
    @listing=Listing.new(listing_params)
    if @listing.save
      flash[:success] = "Your is successfully   save "
    redirect_to listing_path(@listing)
    else
      render 'new'
      end

  end

    def show
      @listing= Listing.find(params[:id])
    end
  def destroy
    @listing= Listing.find(params[:id])
    @listing.destroy
    flash[:danger] = 'Service delete'
    redirect_to listings_path
  end
  def edit
    @listing= Listing.find(params[:id])
  end
  def update
    @listing= Listing.find(params[:id])
    if @listing.update(listing_params)
      flash[:success] = 'Your service was successfully updated'
      redirect_to listing_path(@listing)
    else
      render 'edit'
    end

  end

  private
  def set_listing
    @listing=listing.find(params[:id])
  end
  def listing_params
    params.require(:listing).permit(:title,:description,:city,:contact,:address,:price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end

end

app/controllers/pages_controllers.rb
class PagesController < ApplicationController
  def index

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
   @user=User.new
  end
  def create
    @user=User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to Task Master #{@user.username} "
      redirect_to listings_path
    else
      render 'new'
      end
  end
  def edit
    @user=User.find(params[:id])
  end
  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Your Account has been Updated"
      redirect_to listings_path
    else
      render 'edit'

    end

  end
  def show
   @user=User.find(params[:id])
  end
  private
  def user_params
    params.require(:user).permit(:username,:password,:email,:city,:contact,:address,:avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravater_for(user)

  end
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="container">

  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name,msg|%>
        <div class='alert alert-<%="#{name}" %>'>
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div,msg, :id => "flash_#{name}" if msg.is_a? (String)%>
        </div>

    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

     <li> <%= link_to 'Task Master',root_path,class:'navbar-brand', id:'logo' %></li>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li ><a href="#">Link <span class="sr-only"></span></a></li>
        <li><a href="#">Link</a></li>

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Buy Service</a></li>
        <li> <%= link_to 'Post Service' ,new_listing_path %></li>

        <li><a href="#">How we work</a></li>
        <li ><%= link_to 'Sign Up',signup_path %>


      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navigation' %>
<%= render 'layouts/messages' %>

<%= yield %>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/listings/_form.html.erb
<%=render 'shared/errors' ,obj:@listing%>


<div class="row">
  <div class="container">
    <div class="col-xs-12">


<%= form_for  @listing, :html => {class:"form-horizontal",role:"form"}  do |f| %>
        <div class="form-group">
              <div class=" control-label col-sm-2">
                <%= f.label :title, "Item Name:" %>
                </div>
          <div class="col-sm-8">
            <%= f.text_field :title, class: "form-control", placeholder:"Enter Item name" ,autofocus:true%>
          </div>
              </div>

          <div class="form-group">
            <div class=" control-label col-sm-2">
              <%= f.label :description, 'Item Description:' %>
            </div>
            <div class="col-sm-8">
              <%= f.text_area :description, rows: 8,class: "form-control", placeholder:"Item Description" %>
            </div>
          </div>
          <div class="form-group">
            <div class=" control-label col-sm-2">
              <%= f.label :city, "City:" %>
            </div>
            <div class="col-sm-8">
              <%= f.text_field :city, class: "form-control", placeholder:"City" %>
            </div>
          </div>
          <div class="form-group">
            <div class=" control-label col-sm-2">
              <%= f.label :contact, "contact:" %>
            </div>
            <div class="col-sm-8">
              <%= f.text_field :contact, class: "form-control", placeholder:"contact" %>
            </div>
          </div>
          <div class="form-group">
            <div class=" control-label col-sm-2">
              <%= f.label :address, "Address:" %>
            </div>
            <div class="col-sm-8">
              <%= f.text_field :address, class: "form-control", placeholder:"Address" %>
            </div>
          </div>
          <div class="form-group">
            <div class=" control-label col-sm-2">
              <%= f.label :price, "Price:" %>
            </div>
            <div class="col-sm-8">
              <%= f.text_field :price, class: "form-control", placeholder:"Price" %>
            </div>
          </div>
          <div class="form-group">
            <div class=" control-label col-sm-2">

            </div>
            <div class="col-sm-offset-2 col-sm-10">
              <%= f.submit class: "btn btn-lg  btn-primary" %>
            </div>
          </div>

<%end %>
      <div class="col-xs-4 col-xs-offset-4 ">
       [ <%=link_to 'Cancel Request and return to Service Listing',root_path %> ]

      </div>

    </div>
  </div>

</div>

app/views/listings/edit.html.erb
<h1 align="center">Update Service</h1>
<%= render 'form' %>

app/views/listings/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="jumbotron text-center">
      <h2>Find A Service</h2>
      <form>
        <div class="col-md-6 col-md-offset-3">
          <div class="input-group input-group-lg">
            <input type="text" class="form-control" placeholder="Search Service">
            <span class="input-group-addon">@</span>
          </div>
        </div>
      </form>
      <br><br>
    </div>
  </div>
</div>



 <h1 align="center">Featured Service</h1>

 <% @listings.each  do |listing| %>

    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
        <div class="listing-title">
          <%= link_to listing.title, listing_path(listing)%>
        </div>
        <div class="listing-body">
          <%= truncate(listing.description,length:100)%>
          <p>City: <%=listing.city %></p>
          <p>Contact: <%=listing.contact %></p>
          <p><%=listing.address %></p>
          <p><%=listing.price %></p>
          <p><%=time_ago_in_words( listing.created_at) %></p>
        </div>
          <div class="listing-action">
            <%=link_to 'Edit service',edit_listing_path(listing),class:"btn btn-xs btn-primary" %>
            <%=link_to 'Delete',listing_path(listing),method: :delete,
                       data:{confirm:'do you want to delete'},class:"btn btn-xs btn-danger" %>

          </div>
        </div>


      </div>
    </div>

    <%end %>

app/views/listings/new.html.erb
<h1 align="center">Post Service</h1>
<%= render 'form' %>

app/views/listings/show.html.erb
<h1 align="center"><%= @listing.title %></h1>
<div class="well col-xs-8 col-xs-offset-2">
  <h4 class="center description">
      Description
      <p><%= simple_format(@listing.description) %></p>

</h4>
  <span style="font-size:1.3em">
  <p>City: <%=@listing.city %></p>
  <p>Contact: <%=@listing.contact %></p>
  <p><%=@listing.address %></p>
  <p><%=@listing.price %></p>
  <p><%=time_ago_in_words( @listing.created_at) %></p>
    </span>
  <div class="listing-action">
    <%=link_to 'Edit service',edit_listing_path(@listing),class:"btn btn-xs btn-primary" %>
    <%=link_to 'Delete',listing_path(@listing),method: :delete,
               data:{confirm:'do you want to delete'},class:"btn btn-xs btn-danger" %>
    <%=link_to 'back to service',root_path, class:'btn btn-xs btn-success' %>
  </div>

</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(obj.errors.count,'error')%>
              prohibited this Service fron being save:
            </h2>
            <div class="panel-body">
              <ul>
                <%obj.errors.full_messages.each  do  |msg| %>

                    <li><%= msg %></li>

                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

<% end %>

app/views/users/_form.html.erb
<%=render 'shared/errors' ,obj:@user%>


<div class="row">
  <div class="container">
    <div class="col-xs-12">


      <%= form_for  @user, :html => {class:"form-horizontal",role:"form"}  do |f| %>

          <div class="form-group">
            <%= f.label :avatar,'Image', class: 'col-sm-2 control-label'  %>
            <div class="col-sm-6">
              <%= f.file_field :avatar %>
            </div>
          </div>
          <div class="form-group">
            <div class=" control-label col-sm-2">
              <%= f.label :username, "Username:" %>
            </div>
            <div class="col-sm-8">
              <%= f.text_field :username, class: "form-control", placeholder:"Enter username" ,autofocus:true%>
            </div>
          </div>
          <div class="form-group">
            <div class=" control-label col-sm-2">
              <%= f.label :password, "Password:" %>
            </div>
            <div class="col-sm-8">
              <%= f.password_field :password, class: "form-control", placeholder:"Enter Password" %>
            </div>
          </div>

          <div class="form-group">
            <div class=" control-label col-sm-2">
              <%= f.label :email, 'Email:' %>
            </div>
            <div class="col-sm-8">
              <%= f.email_field :email, rows: 8,class: "form-control", placeholder:"email" %>
            </div>
          </div>

          <div class="form-group">
            <div class=" control-label col-sm-2">
              <%= f.label :city, "City:" %>
            </div>
            <div class="col-sm-8">
              <%= f.text_field :city, class: "form-control", placeholder:"City" %>
            </div>
          </div>
          <div class="form-group">
            <div class=" control-label col-sm-2">
              <%= f.label :contact, "Contact:" %>
            </div>
            <div class="col-sm-8">
              <%= f.text_field :contact, class: "form-control", placeholder:"contact" %>
            </div>
          </div>
          <div class="form-group">
            <div class=" control-label col-sm-2">
              <%= f.label :address, "Address:" %>
            </div>
            <div class="col-sm-8">
              <%= f.text_field :address, class: "form-control", placeholder:"Address" %>
            </div>
          </div>

          <div class="form-group">
            <div class=" control-label col-sm-2">

            </div>
            <div class="col-sm-offset-2 col-sm-10">
              <%= f.submit (@user.new_record? ? 'Sign Up' :'Update Profile'), class: "btn btn-lg  btn-primary" %>
            </div>
          </div>

      <%end %>
      <div class="col-xs-4 col-xs-offset-4 ">
        [ <%=link_to 'Cancel Request and return to Service Listing',root_path %> ]

      </div>

    </div>
  </div>

</div>

app/views/users/edit.html.erb
<h1 align="center">Update Profile</h1>
<%= render 'form'%>

app/views/users/new.html.erb
<h1 align="center">Create Profile</h1>
<%= render 'form'%>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%=@user.username %>'s page</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%=gravartor_for @user %>
  </div>
</div>
<h2 align="center"><%=@user.username%>'s Listings</h2>